### ISSUE TITLE
[BUG] Savegame location for installed Ren'Py games is wrongly detected as unused

### ISSUE THREAD

**Issue by seeeeew** [pawel-0/xdg-unused-data#28]
**Describe the bug**
The default savegame location for Ren'Py games (`~/.renpy`) is detected as unused despite containing saves for multiple installed games.

**Terminal output**
```
user@machine:~$ ./xdg-unused-data/xdg-unused-data.sh 
Some xdg-basedir envirnoment variables are not defined. Fallbacks will be used!

Missing:
- $XDG_DATA_HOME
- $XDG_CONFIG_HOME
- $XDG_STATE_HOME
- $XDG_CACHE_HOME

[Ren’Py]: /home/user/.renpy (146.05 MB)

Summary:
 Total files: 1
 Total size: 146.05 MB

```

**System**
 - Distro: Ubuntu 22.04.2 LTS
 - Shell: bash

**Additional context**
Ren'Py games usually don't contain an executable named `renpy`, but they still store their savegames in `~/.renpy`. I think it's very dangerous to list the folder as unused just because the executable isn't found. Someone playing a Ren'Py game might have never even heard of the name, which could easily lead to them accidentally deleting all their saves based on the output of this script. I'd suggest removing Ren'Py from detection completely, because Ren'Py games are distributed in various different ways and have no fixed install location, which makes it close to impossible to detect whether they're installed.

**Comment by pawel-0** [comment]
Thank you for creating a Bug report. I fixed the issue
