### ISSUE TITLE
[BUG] .sdkman Shows Even When SDKMAN is Installed

### ISSUE THREAD

**Issue by FOSSProponent9436** [pawel-0/xdg-unused-data#29]
**Describe the bug**
When running the script, .sdkman shows even when SDKMAN is still installed (sdk command works). Not only that, it shows up twice.

**Terminal output**
```
Some xdg-basedir envirnoment variables are not defined. Fallbacks will be used!

Missing:
- $XDG_DATA_HOME
- $XDG_CONFIG_HOME
- $XDG_STATE_HOME
- $XDG_CACHE_HOME

[sdkman]: /home/admin/.sdkman (291.35 MB)
[sdkman]: /home/admin/.sdkman (291.35 MB)
```
**System**
 - Distro: fedora
 - Shell: bash

**Additional context**
Installed through script from here: https://sdkman.io/

**Comment by pawel-0** [comment]
Thanks for reporting. I remove sdkman from support: 

> sdk is not a real command. It's created by a sdkman bash script which has to be sourced and appears to be some type of alias. This behavior is right now not supported and sdkman therefore removed

I also created a new bug for the duplicated output: #33
