### ISSUE TITLE
Syncthing config files are incorrectly detected as unused

### ISSUE THREAD

**Issue by ButteredCats** [pawel-0/xdg-unused-data#34]
**Describe the bug**
Syncthing's files are detected as unused and reported as "Syncthing GTK" when Syncthing is installed and Syncthing-GTK is not.

**Terminal output**
```
[Syncthing GTK]: /home/cat/.config/syncthing (360.23 MB)

Summary:
 Total files: 1
 Total size: 360.23 MB
```

**System**
 - Distro: Arch
 - Shell: zsh

**Additional context**
Syncthing-GTK's folder is `syncthing-gtk` under the `.config` directory.
Installing and then uninstalling Syncthing-GTK produces this output:
```
[Syncthing GTK]: /home/cat/.config/syncthing (360.23 MB)
[Syncthing GTK]: /home/cat/.config/syncthing-gtk (685 B)

Summary:
 Total files: 2
 Total size: 360.23 MB
 ```

**Comment by pawel-0** [comment]
I split syncthing and syncthing-gtk so they can be detected separately. This should solve the problem
