### ISSUE TITLE
[BUG] Settings folders are printed even though they are used by another installed executable

### ISSUE THREAD

**Issue by mxmlnkn** [pawel-0/xdg-unused-data#44]
**Describe the bug**

The .wine folder is printed even though wine is installed. The printout is labeled Winetricks, which is not installed.
The problem seems to be that .wine appears in the applications jsons for WineTricks and for Wine.
I think xdg-unused-data should only print out folders that have none of the possible executables associated.

**Terminal output**
```
[Winetricks]: /home/user/.wine (1.79 GB)
```

**System**
 - Distro: Ubuntu
 - Shell: Bash

**Comment by pawel-0** [comment]
thanks for reporting the bug. You are absolutely right. I removed winetricks.json since there is no dedicated folder for it. I will also review all other JSON files.
